## Purpose: 
This Notebook is designed as an attempt to implement the Gollini 2014 method of extracting latent positions from (multiple) network view(s).

The method implements a EM - algorithm in combination with a Variational methods approach to estimation. 

The impact of this is twofold: 

Firstly, The speed gain should be significant in comparison to alternative (bayesian) methods. 

Secondly, The extraction of latent positions should be beneficial in relation to controlling for selection effects. 


## The algorithm: 

The algorithm consist of two steps: The E and the M step. Overall they are both optimization steps in the variational methods framework.

#### E - Step:  estimate z_i and Sigma_i 

#### M - Step: Estimate alpha_M_i  and alpha_V_i^2


    

This Step designs a function that can estimate z_i in the single use case Next we will attempt a vectorized approach


In [2]:
from numpy.linalg import norm, det
from numpy.random import multivariate_normal
import numpy as np
from numpy.random import uniform, normal
from scipy.spatial.distance import pdist
from scipy.spatial.distance import squareform
import timeit
import seaborn as sns
import pandas as pd

In [3]:
## Simulate companion matrix: 


def Companion_matrix(Z, alpha_0, alpha_1, N, threshold):
    
    dist_c = squareform(pdist(Z))
    
    dist_c = dist_c*dist_c

    # latent utility nxn matrix:

    alpha_0_nxn = np.ones((N,N))*alpha_0

    alpha_1_nxn = dist_c*alpha_1

    # noise term: - random gaussian noise where the upper diagonal is taken and transposed and the diagonal is divided by two
    #E_nxn = normal(size=(N,N))
    E_nxn = np.triu(normal(size=(N,N)))
    E_nxn = E_nxn + E_nxn.T
    np.fill_diagonal(E_nxn,0)

    latent_utility = alpha_0_nxn + alpha_1_nxn + E_nxn

    return np.where(latent_utility > threshold,1,0)


In [460]:
# parameters for testing: 
D=4
N = 5000

# Setting the true mean and cov-var of Z
mean_z = np.zeros(D)
cov_z  = np.identity(D)
alpha_0 = 0
alpha_1 = -0.3

# generating Z:

Z = multivariate_normal(mean_z, cov_z, N)

# Companion matrix - This function is a bit unstable and needs to be better constructed - it will do the trick though

Y = Companion_matrix(Z,  alpha_0, alpha_1, N,  0)

print("Z dim:", np.shape(Z))
print("Y dim:", np.shape(Y))
print(Y)

Z dim: (5000, 4)
Y dim: (5000, 5000)
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]


In [461]:
#prior VARIANCE
alpha_v_prior = 1
alpha_m_prior = 0


# this function should produce a gradient of size D*1:
# for N = 1000 this precedure takes roughly 3 seconds: If this proves to be too slow one can consider working with tensors
def zi_Gradient(i, D, sigma_est, Z_1, alpha_m, alpha_v):
    
    from numpy.linalg import inv as inv
    
    #error handling
    if D != np.shape(sigma_est)[0]:
        raise ValueError("dimension of sigma_est is not equal to dimensionality D")

    # (I + 4sigma)^-1 DxD matrix
    alpha=np.identity(D) +  4*sigma_est
    alpha_inv = inv(alpha)
    
    # Z_ij = (zi - zj) (N-1)xD matrix (i excluded)
    z_i= Z_1[i,:]
    Z_j = np.delete(Z_1, (i), axis=0)
    Z_ij = z_i - Z_j
    
    
    # c *exp(z_ij*alpha_inv*z_ij^T) = c*exp(quadform)
    
    c = np.sqrt(det(alpha))/np.exp(alpha_m + 0.5*alpha_v)
        
    def quadform(Z_ij, alpha_inv):
        ZalphaZT = np.zeros(np.shape(Z_ij)[0])
        for j in range(np.shape(Z_ij)[0]):
             ZalphaZT[j]= Z_ij[j,:].dot(alpha_inv).dot(Z_ij[j,:].T)
        return ZalphaZT
        
    
    exp_quadform = np.exp(quadform(Z_ij, alpha_inv))
    
    
    
    # beta = [1 + c*exp(quadform)^-1] (N-1)*1 matrix
    
    beta = 1/(1 + c*exp_quadform)
    
    # Sum_j (z_i - z_j)*beta (N-1)*D matrix
        
    Sum_j = (Z_ij.T * beta).T
    
    # Next we want to get alpha_inv * sum over N dimension to get a D*1
    
    sum_j = np.sum(Sum_j,axis=0)
    
    # returns the gradient
    
    return -2*alpha_inv.dot(sum_j)

zi_Gradient(1, D, cov_z, Z, alpha_m_prior, alpha_v_prior)



array([-38.90402483, -16.02000226,  22.05283843, -10.82787057])

In [462]:
# This function should produce a Hessian of size DxD
# -2*alpha_inv*sum_j(1 + c*exp(quadform))^-1 * [I - Z_ij Z_ij^T*alpha_inv/[1+ c*exp(quadform)]]
def zi_Hessian(i, D, sigma_est, Z_1, alpha_m, alpha_v):
    from numpy.linalg import inv as inv
    # The Hessian is composed of alpha*beta*gamma (DxD * 1x1 * DxD)
    
    # alpha - part: DxD matrix
    # (I + 4sigma)^-1 DxD matrix
    alpha=np.identity(D) +  4*sigma_est
    alpha_inv = inv(alpha)
    
    # beta  - part: (N-1)x1
    # Z_ij = (zi - zj) (N-1)xD matrix (i excluded)
    z_i= Z_1[i,:]
    Z_j = np.delete(Z_1, (i), axis=0)
    Z_ij = z_i - Z_j
    
    
    # c *exp(z_ij*alpha_inv*z_ij^T) = c*exp(quadform)
    
    c = np.sqrt(det(alpha))/np.exp(alpha_m + 0.5*alpha_v)
        
    def quadform(Z_ij, alpha_inv):
        ZalphaZT = np.zeros(np.shape(Z_ij)[0])
        for j in range(np.shape(Z_ij)[0]):
             ZalphaZT[j]= Z_ij[j,:].dot(alpha_inv).dot(Z_ij[j,:].T)
        return ZalphaZT
        
    
    exp_quadform = np.exp(quadform(Z_ij, alpha_inv))
    
    # the beta part (N-1)*1
    beta = 1/(1 + c*exp_quadform)
    
    #now we broadcast beta into a (N-1)xDxD matrix where DxD consist of ones*beta[i]
    N = np.shape(beta)[0]
    def broadc_NDD(beta,D):
        # This function broadcasts from a (N-1)x1 --> (N-1)xDxD (where DxD(i) = Ones*beta[i])
        return np.reshape(np.repeat([np.repeat(beta,D)],D, axis=0).T,(N,D,D))
    
    beta_NDD = broadc_NDD(beta,D)
    
    # gamma = = 1/num*denom = 1/num * Z_ijZ_ij.T * alpha_inv (1x1)
    
    # Z_ij * Z_ij.T = Dx1 1xD = DxD 
    
    Zij=np.reshape(Z_ij,(shape(Z_ij)[0],D,1))
    ZijT=np.reshape(Z_ij,(shape(Z_ij)[0],1,D))
    
    denom = 2*(Zij * ZijT).dot(alpha_inv)
    num = np.reshape(1 + 1/c * 1/exp_quadform,(np.shape(Z_ij)[0],1,1))
    identity = np.identity(D)
    
    gamma_NDD = identity - denom * num
    
    #Hessian = -2 alpha_inv * sum(gamma_NDD * beta_NDD)
    
    Hessian =-2*alpha_inv.dot(np.sum(gamma_NDD * beta_NDD, axis = 0))
    
    return Hessian
    

def zi_Gradient_Hessian(N ,D, sigma_est, Z_1, alpha_m, alpha_v):
    Gradient = np.zeros((N,D))
    Hessian = np.zeros((N,D,D))
    for i in range(N):
        Gradient[i,:]=zi_Gradient(i, D, sigma_est, Z_1, alpha_m, alpha_v)
        Hessian[i,:,:] = zi_Hessian(i, D, sigma_est, Z_1, alpha_m, alpha_v)
    
    #Gradient = np.reshape(Gradient,(N,D,1))
    
    return (Gradient, Hessian)
        
Gradient, Hessian = zi_Gradient_Hessian(N, D, cov_z, Z, alpha_m_prior, alpha_v_prior)

print(shape(Gradient))
print(shape(Hessian))


(5000, 4)
(5000, 4, 4)


In [482]:
## This section attempts to build a fully vectorized update step for zi:

def Z_update(Y, D, Z_1, sigma_est, alpha_m, alpha_v, ):
    
    
    # Defensive programming:
    
    if np.diag(Y).any() != 0: 
        raise ValueError("The diagonal of Y is non-Zero")

    # Vectorized sum over 
    sum_Y = np.reshape(np.repeat(Y.T + Y, D),(shape(Y)[0],shape(Y)[0],D))
    sum_YZ = sum_Y * Z_1
    
    # summing over j
    
    sum_Yj = np.sum(sum_Y, axis=1)
    sum_Yj = np.reshape(sum_Yj[:,0],(shape(sum_Y)[0],1,1))   #Nx1x1
    sum_YZj = np.sum(sum_YZ, axis=1)
    
    # Denominator
    
    
    #print(shape(sum_YZj))
    #print(shape(Gradient))
    #print(shape(Hessian))
    #print(shape(Z_1))
    
    #printHessian.dot(np.reshape(Z_1,(5,4,1))))
    
    Z_1_ND1 = np.reshape(Z_1,(shape(Z_1)[0],D,1))
    
    
    denom = sum_YZj - Gradient + np.squeeze(np.matmul(Hessian,Z_1_ND1))
    # numerator
    
    I  = np.zeros((shape(sum_Y)[0],D,D)) + np.eye(D)

    num =1/(2*alpha_v) + I*sum_Yj + Hessian
    
    
    
    # VERY UNSURE IF THIS PROVIDES THE CORRECT SOLUTION
    # ax = b <=> x = a^-1*b
    z_i = np.linalg.solve(num,np.reshape(denom,(shape(Y)[0],D,1)))

    return z_i

print(shape(Z_update(Y, D, Z, cov_z, alpha_m_prior, alpha_v_prior)))

    

(5000, 4, 1)


In [276]:
def zi_update(i, Y, Z_1, D, sigma_est, alpha_m, alpha_v):
    denom_Y = np.delete(Y[i,:] + Y[:,i],i,0)
    denom_Y = np.delete(denom_Y,i,0)
    print(denom_Y)
    sum_denom = 1
    nom = 1 pr
    
zi_update(1, Y, Z, D, cov_z, alpha_m_prior, alpha_v_prior)
    

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2
 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 2 0 2 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0
 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [277]:
a = np.array([1,2,3,4])
print(np.delete(a,,0))

SyntaxError: invalid syntax (<ipython-input-277-fb6c132071f3>, line 2)

In [ ]:
## from numpy import shape
N=3
D=2

a = np.array([[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]])
b = np.array([1,2,3])

test = np.repeat(b,2)
test = np.repeat([test],2, axis=0)
test2 = np.reshape(test.T,(3,2,2))
print(shape(test2))
print(test2)
print(a)

In [ ]:
a - test2

In [ ]:
a = np.array([[1,2,3], [4,6,7]])
b= np.reshape(a,(2,1,3))
c = np.reshape(a.T,(2,1,3))
print(b)
print(c)

In [169]:
a = np.array([[1,2],[2,3]])
b = np.array([[2,3],[4,6]])
print(a*b)
print(a.dot(b))

[[ 2  6]
 [ 8 18]]
[[10 15]
 [16 24]]


In [382]:
M = np.ones((2, 3))
a = np.arange(3)
a

array([0, 1, 2])

In [481]:
a = np.zeros((5,3,3)) + np.eye(3)
print(a)
print(shape(a))

b =np.reshape(np.ones(3),(3,1))
print(b)
print(shape(b))

c = np.matmul(a,b)
print(c)
print(shape(c))

[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]]
(5, 3, 3)
[[1.]
 [1.]
 [1.]]
(3, 1)
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]
(5, 3, 1)
